abort if input file names contain whitespace or quote characters

diff --git a/fax/faxspool.in b/fax/faxspool.in
--- a/fax/faxspool.in
+++ b/fax/faxspool.in
@@ -3,7 +3,7 @@
 # faxspool - sample script how to spool fax input data to a spool
 #            directory, creating jobs to be run by faxrunq
 #
-# sccsid: $Id: faxspool.in,v 4.22 2002/11/23 15:14:57 gert Exp $ (c) Gert Doering
+# sccsid: $Id: faxspool.in,v 4.23 2003/01/21 13:27:12 gert Exp $ (c) Gert Doering
 #
 # syntax: faxspool [flags] <phone-number> <job(s)>
 #
@@ -26,6 +26,9 @@
 #  3.10.93: use "hp2hig3" for hp-pcl4-files (cl)
 # 19.10.93: phone directories (caz)
 # $Log: faxspool.in,v $
+# Revision 4.23  2003/01/21 13:27:12  gert
+# abort if input file names contain whitespace or quote characters
+#
 # Revision 4.22  2002/11/23 15:14:57  gert
 # revert 4.14 -> 4.15 change: faxqueue_done is now back in $FAX_SPOOL_OUT
 # (new permission concept, faxrunq/faxrunqd no longer running as root)
@@ -577,11 +580,15 @@ else
 fi
 
 #
-# check, if all the files exist & are readable
+# check, if all the file names are "clean", that the files exist & are readable
 #
 
 for file
 do
+    if [ `echo "$file" | tr -d ' \011\012\015\047\140"' ` != "$file" ]
+    then
+	$echo "$0: invalid characters in file name '$file'!" >&2 ; exit 5
+    fi
     if [ ! -r $file -a x$file != x- ]
     then
 	$echo "$0: cannot open '$file'!" >&2 ; exit 5
