Implement "start-end" syntax for "-t <time>" flag small bugfix for "echo" message after successful queueing "with -t"

diff --git a/fax/faxspool.in b/fax/faxspool.in
--- a/fax/faxspool.in
+++ b/fax/faxspool.in
@@ -3,7 +3,7 @@
 # faxspool - sample script how to spool fax input data to a spool
 #            directory, creating jobs to be run by faxrunq
 #
-# sccsid: $Id: faxspool.in,v 4.35 2007/08/21 10:33:42 gert Exp $ (c) Gert Doering
+# sccsid: $Id: faxspool.in,v 4.36 2010/06/04 12:45:36 gert Exp $ (c) Gert Doering
 #
 # syntax: faxspool [flags] <phone-number> <job(s)>
 #
@@ -26,6 +26,10 @@
 #  3.10.93: use "hp2hig3" for hp-pcl4-files (cl)
 # 19.10.93: phone directories (caz)
 # $Log: faxspool.in,v $
+# Revision 4.36  2010/06/04 12:45:36  gert
+# Implement "start-end" syntax for "-t <time>" flag
+# small bugfix for "echo" message after successful queueing "with -t"
+#
 # Revision 4.35  2007/08/21 10:33:42  gert
 # add "-" to list of permitted characters in FDATE
 #
@@ -529,17 +533,26 @@ do
 	    shift ; shift
 	    ;;
 # set first time to send fax
-	-t) if expr "$2" : "[0-2][0-9]:[0-9][0-9]$" >/dev/null
+	-t) if expr "$2" : "[0-2][0-9]:[0-5][0-9]$" >/dev/null
 	    then
 		h=`expr "$2" : "\(..\)"`
 		m=`expr "$2" : "..:\(..\)"`
-		if [ "$h" -gt 23 -o "$m" -gt 60 ]
+		if [ "$h" -gt 23 ]
 		then
 		    $echo "Invalid time specified: $h:$m" >&2; exit 2
 		fi
 		TIME="$h$m"
+	    elif expr "$2" : "[0-2][0-9]:[0-5][0-9]-[0-2][0-9]:[0-5][0-9]$" >/dev/null
+	    then
+		h1=`expr "$2" : "\(..\)"`
+		h2=`expr "$2" : "..:..\-\(..\)"`
+		if [ "$h1" -gt 23 -o "$h2" -gt 23 ]
+		then
+		    $echo "Invalid time range specified: $2" >&2; exit 2
+		fi
+		TIME="`echo "$2" | tr -d ':'`"
 	    else
-		$echo "Time must be in <hh:mm> format." >&2; exit 2
+		$echo "Time specification (-t) must be in <hh:mm> or <hh:mm-hh:mm> format." >&2; exit 2
 	    fi
 	    shift ; shift
 	    ;;
@@ -995,6 +1008,6 @@ else
     if  [ -z "$TIME" ] ; then
 	$echo "\nFax queued successfully. Will be sent at next \`\`faxrunq'' run.\n"
     else
-	$echo "\nFax queued successfully. Will be sent at first \`\`faxrunq'' run\nafter the specified send time '$TIME' has been reached\n."
+	$echo "\nFax queued successfully. Will be sent at first \`\`faxrunq'' run\nafter the specified send time '$TIME' has been reached.\n"
     fi
 fi
